create table ticket
(
    id           bigint generated by default as identity
        constraint ticket_pkey
            primary key,
    buy          boolean,
    company_name varchar(255),
    cost         double precision,
    destination  varchar(255),
    reserved     boolean,
    beginning    varchar(255),
    arrival      timestamp,
    departure    timestamp,
    client_id    bigint
        constraint fkj2rjr6m31hp7m00tm1hdxckov
            references client,
    flight_id    bigint
        constraint fkfju27cbcbl1w16qeora1r636q
            references flight
);

alter table ticket
    owner to postgres;

